version: '3.8'

services:
  db:
    container_name: wp-base
    image: mysql:8.0
    healthcheck:
      test: ["CMD", "mysql", "-uroot", "-p${MYSQL_ROOT_PASSWORD}", "-e", "SELECT * FROM mysql.user WHERE User='root' AND Host='localhost';"]
      interval: 10s
      timeout: 10s
      retries: 10
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_USER: ${WORDPRESS_DB_USER}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql

  site:
    container_name: wp-site
    depends_on:
      db:
        condition: service_healthy
    build: ./wp-site/
    links:
      - db
    ports:
      - 80:80
    env_file:
      - .env
    volumes:
      - site:/var/www/html

  pma:
    container_name: wp-pma
    image: phpmyadmin:latest
    links:
      - db
    ports:
      - 8081:80
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      #PMA_ARBITRARY: 1
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

volumes:
  site:
  data: